# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d3085d4c891c0b912c8db7992c2bcddab05be4b7437a5a4c71726cf79ddae5a54e7a205ab217a10873c4f808838353b93316b3ba4f32721e01ae3fea3c7a90e

test:
  secret_key_base: ad02245eef24d59d9654cd05c2ee9430a0d4175e3a6223334bb184275351b65b1aa1ac84d7527c8a1e2cc8726de40fc213659e4465a945f320e544371335db68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
